project:
  type: website
  title: "Explora Eventos Culturales en la CDMX"
  output-dir: _site

website:
  title: "Explora Eventos Culturales en la CDMX"
  navbar:
    left:
      - text: "Eventos"
        href: "Explora Eventos Culturales en la CDMX.qmd"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
