version = 0.1

[default.deploy.parameters]
stack_name = "cultura-cdmx-sam"
resolve_s3 = true
s3_prefix = "cultura-cdmx-sam"
region = "mx-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["PlaywrightLambda=829489762414.dkr.ecr.mx-central-1.amazonaws.com/culturacdmxsam2c2f378c/playwrightlambda7e2d5b91repo"]
