default:
  deploy:
    parameters:
      stack_name: cultura-cartelera-cdmx
      resolve_s3: true
      s3_prefix: cultura-cartelera-cdmx
      region: mx-central-1
      confirm_changeset: true
      capabilities: CAPABILITY_IAM
version: 0.1
